### ISSUE TITLE
rosbag for fusion testing

### ISSUE THREAD

**Issue by liuXinGangChina** [EPVelasco/lidar-camera-fusion#13]
Hi, Your work looks fantastic. @EPVelasco 
Is it possible to provide a **camera-lidar fusion bag** for quick-testing the fusion part?

**Comment by EPVelasco** [comment]
Hi, I have uploaded a rosbag in the ros launch [description](https://github.com/EPVelasco/lidar-camera-fusion#ros-launch) to test package.

**Comment by liuXinGangChina** [comment]
> Hi, I have uploaded a rosbag in the ros launch [description](https://github.com/EPVelasco/lidar-camera-fusion#ros-launch) to test package.

thanks for your great work, the fusion looks fantastic. I notice that you are working on calibrate camera-lidar H matrix, maybe this project may help you [https://github.com/koide3/direct_visual_lidar_calibration]( this tool works for me)
