### ISSUE TITLE
type of extrinsic parameters

### ISSUE THREAD

**Issue by JaceFYP** [EPVelasco/lidar-camera-fusion#17]
Hi you mentioned you used lidar_camera_calibration https://github.com/ankitdhall/lidar_camera_calibration to generate extrinsic parameters to be used in this package. I see that it "transform all the points in the LiDAR frame to the (monocular) camera frame". What if I used a different package for lidar-cam calibration to generate extrinsic parameters which "transforms the camera frame (parent) into the lidar frame (child)"? Am I still able to use those extrinsic parameters? When I try to I don't see the fusion (pcOnImage and points2). However, when I use your default parameters from this package I do. I would appreciate any input, thank you.

**Comment by EPVelasco** [comment]
Hello, the calibration package I use has a very specific camera reference system. You can see this in the following [issue](https://github.com/EPVelasco/lidar-camera-fusion/issues/3)

**Comment by JaceFYP** [comment]
Hi thank you for your reply, I really appreciate it. Sorry I'm not too knowledgeable on this but your package has helped me greatly in my school project. I would like to ask a few things.

1. The initial rotation that you used, is it not generated through calibration? I do have my camera (PS3 Eye Camera) taped directly on top of my lidar (Velodyne VLP16). However, when I generated the extrinsic parameters, for roll pitch yaw, I got these values (-1.4594, -0.0281, -1.3962). Should I instead use (0 0 0)?
Transformation: My final rotation matrix [ 0.0113 0.0210 0.2350] radians. In the [line](https://github.com/EPVelasco/lidar_camera_fusion/blob/main/src/lidar_camera_node.cpp#L326) there is a rotation to align the camera and lidar axes. This internal rotation is [-1.57, 1.57, 0]. Because I use this axis rotation, I suggest you use an initial rotation of [0 0 0].

2. Would you know how to change the reference axis from existing extrinsic parameters? I tried getting the rotation matrix from my roll pitch yaw angles, then combining it with the translation vector (-0.0576, -0.0109, 0.0602) to form the transformation matrix and then inversing that 4x4 transformation matrix. Then I tried extracting the rotation matrix & translation vector from that to put in the config file of this package but the lidar points were way off the camera image.

I only have a chessboard available to use for this lidar-camera calibration, hence I didn't use the lidar_camera_calibration pacakge.

Thank you in advance for any help you can provide!
