### ISSUE TITLE
some error occurs when launch lidar_camera_node

### ISSUE THREAD

**Issue by ShellWee** [EPVelasco/lidar-camera-fusion#20]
I have the same error when using rosbag that you provided and my data.
My pcl_version is 1.8.1.
I also try to modify cfg_params.yaml.
![Screenshot from 2024-03-31 02-26-07](https://github.com/EPVelasco/lidar-camera-fusion/assets/109591588/1cb94024-e5bb-47b8-bd01-85d4e0fb1d33)
![Screenshot from 2024-03-31 02-25-48](https://github.com/EPVelasco/lidar-camera-fusion/assets/109591588/1a60a079-093e-406c-83b9-d8363571d010)
could you please help me solve this problem? thank you very much!

**Comment by EPVelasco** [comment]
Hi I have recreated from scratch a new repository to replicate the error. But the problem has not occurred.
Could you give me more information, could you create again the repository and try with the rosbag cam_lidar00.bag.

Could you also compile the package again?  I would like to know if you have an error while compiling.

**Comment by ShellWee** [comment]
I create again the repository and rebuild the pcl, then It can work successfully. Thanks again!
![Screenshot from 2024-03-31 03-30-14](https://github.com/EPVelasco/lidar-camera-fusion/assets/109591588/e5390d22-0401-4f48-8a73-6439bd2d8aa9)
