### ISSUE TITLE
Using Ouster instead of Velodyne

### ISSUE THREAD

**Issue by bodisimo** [EPVelasco/lidar-camera-fusion#4]
Hey, My college and me try to use the Code u provided. 
But We use another lidar. Bouth of the Lidars use the Ros datatype Pointcloud2.

We changed the input ros topics and also the launch files. 
All starts without a problem.

If rviz starts, we can see the image from the lidar, and we can configure the inputs, that we can see the image from the camera. But we cant se any fusion.

Can you help us?

**Comment by EPVelasco** [comment]
Hi, could you tell me which Lidar do you use?

I would like to know if the point cloud is projected in laser layers.
The Lidar I use is a VLP-16 and it projects 16 laser layers.

**Comment by bodisimo** [comment]
we use the ouster os1-128-u.
What also comes in mind... is that the image is not shown automaticly with the rviz that you provided. We need to manuly change the input to see the image provided by the camera

**Comment by EPVelasco** [comment]
What camera are you using? Is the camera calibrated with the ouster os1-128-u?.
I used the [Lidar-Camera](https://github.com/ankitdhall/lidar_camera_calibration) package for calibration.

If you don't see the image automatically in RVIZ, it could be because of the wrong image topic name. 

Consider that the package I coded was made for a Lidar with few laser layers to interpolate. If you use a lidar with 128 laser layers, the interpolation could not be done in real-time due to the huge volume of point cloud data.

In the demonstration video, I used a 16-layer lidar and interpolated it up to 10 times, making a virutal 160-layer point cloud. Maybe you don't need to interpolate your os1-128-u lidar, but just have it calibrated correctly with the [Lidar-Camera](https://github.com/ankitdhall/lidar_camera_calibration) package.

**Comment by bodisimo** [comment]
We just saw that we use ros noetic. Do you know if this package is also oke to use?

**Comment by EPVelasco** [comment]
The Lidar-camera calibration has a package branch whit Ros-noetic. [link](https://github.com/ankitdhall/lidar_camera_calibration/tree/implement-noetic-action)
You have to clone the package with that branch name [implement-noetic-action](https://github.com/ankitdhall/lidar_camera_calibration/tree/implement-noetic-action)
```
git clone https://github.com/ankitdhall/lidar_camera_calibration.git -b implement-noetic-action
```
Our Lidar-Camera fusion code was tested with Ros noetic. The results are detailed in this [issue](https://github.com/EPVelasco/lidar-camera-fusion/issues/2)

**Comment by bodisimo** [comment]
Hmm. Would it be possible that you look oder Our Problem? If you help us we will thank with a Little bit of paypal Support :D

**Comment by EPVelasco** [comment]
The purpose of the issues is to let the github community know about the bug and fix it.  You can upload the problem in these messages and we will help you at no cost.  Tell me, what is the problem? have you been able to use the [Lidar-Camera](https://github.com/ankitdhall/lidar_camera_calibration) package?

**Comment by abhishekt711** [comment]
I have calibrated Velodyne HDL-64 LiDAR and camera. I gave the correct input topics in launch file. but i am able to visualize only the LiDAR data and camera image separately. I am not able to visualize fused data and depth detection.Can you Please help.

**Comment by EPVelasco** [comment]
hello can you upload an image of rqt_graph to visualize the nodes and their connections?
To do this in a terminal type:
```
rqt_graph
```

**Comment by abhishekt711** [comment]
![rosgraph](https://user-images.githubusercontent.com/36338604/222685446-6b35ccd1-a5c5-41b8-8a92-11fb87b455f6.png)
Please check the rqt_graph attached here. I am  unable to visualize /pcOnImage_image  /points2 these topics.

**Comment by EPVelasco** [comment]
please only launch the node the lidar_camera_node
```
  roslaunch lidar_camera_fusion vlp16OnImg.launch 
```
This node already performs the point cloud interpolation internally.
This node must subscribe to the /velodyne_points topic. Make sure that the file vlp16OnImg.launch has the correct spelling of the topic name.

**Comment by abhishekt711** [comment]
![rosgraphn](https://user-images.githubusercontent.com/36338604/222730204-ed594f9a-ef8e-4a1d-8201-a21b0949e8e6.png)
I have only launch the node lidar_camera_node with this roslaunch lidar_camera_fusion vlp16OnImg.launch , please find the rqt_graph image now.

**Comment by EPVelasco** [comment]
The lidar_camera_node node is not subscribing to the image topic. Checks the name of the image topic going to the node. If you don't know how to see the topics of your rosbag use:
```
rosbag info name_of_your_rosbag.bag
```
As you are using a rosbag I suggest you use the launch vlp16OnImg_offline.launch.
```
  roslaunch lidar_camera_fusion vlp16OnImg_offline.launch 
```
The lidar camera node needs the topics **/velodyne_points** and the image topic **/camera/color/image_raw**. 
Check the topic names of your rosbag and modify the file [vlp16OnImg_offline.launch](https://github.com/EPVelasco/lidar-camera-fusion/blob/main/launch/vlp16OnImg_offline.launch).

**Comment by abhishekt711** [comment]
yes my image topic is /pylon_camera_node/image_raw. and i had already changed this.

**Comment by abhishekt711** [comment]
unable to visualize /points2 topic and image is only coming in /pconimage_image topic 
![rosgraphnew](https://user-images.githubusercontent.com/36338604/222822817-443ac33d-1636-404e-b8e0-882626ea9d1b.png)
![rviz_screenshot_2023_03_04-02_01_17](https://user-images.githubusercontent.com/36338604/222823377-4f9f2915-14e6-4ed4-b64f-c53d8a97c295.png)
![rviz_screenshot_2023_03_04-02_01_58](https://user-images.githubusercontent.com/36338604/222823393-07f3be25-6ce1-4ceb-916e-d63e8b0af8be.png)

i can visualize velodyne_points topic but not /points2. also pconImage_Image and image are visualized as same in rviz

**Comment by EPVelasco** [comment]
Could you check if the image and point cloud topics of your rosbag have the time in the header? 

The lidar camera node subscribes to both topics by synchronizing them with the time stamp in the topic header.

**Comment by abhishekt711** [comment]
yes it have time stamp. few month back, with some other algorithm i have already projected this point cloud on image. then applied yolo on projected point cloud. my next doubt is how to calculate the depth of that obstacle?

**Comment by EPVelasco** [comment]
Could you show me the roslaunch. file? I want to see the parameters you have set. 

I also want to know the calibration matrix of the cfg folder.

**Comment by abhishekt711** [comment]
please check the cfg file and launch file. Also can u see the 2nd pic and help me in finding the depth of obstacle. 
<img width="752" alt="Screenshot 2023-03-03 213143" src="https://user-images.githubusercontent.com/36338604/222833621-09fd6f12-520b-4491-ba20-401facb4cafa.png">
can u please see this ,  i have projected pointcloud on image before and applied yolo on that now i want to calculate depth of the obstacle, please check the image
<img width="710" alt="Screenshot 2023-03-03 212952" src="https://user-images.githubusercontent.com/36338604/222833862-f598b6e0-c43a-4a3d-859f-5d42b1f53872.png">

**Comment by EPVelasco** [comment]
Have you obtained the rlc and tlc values with any calibration method? 
If you have not used the one suggested in the redme, it may be that your coordinate system is different from the one I used.
Try modifying the code lines 326, 327 and 328 of [node](https://github.com/EPVelasco/lidar-camera-fusion/blob/main/src/lidar_camera_node.cpp#L326).

And set them to: 
pc_matrix(0,0) = P_out->points[i].x;   
pc_matrix(1,0) = P_out->points[i].y;   
pc_matrix(2,0) = P_out->points[i].z;

**Comment by EPVelasco** [comment]
To calculate the depth of an object detected by yolo it is necessary to know the pixel coordinates of the detected objects, then the bounding box of each detected object is traversed with two FOR loops and inside the loop you ask the value of the depth point that is projected onto the image plane.

Then, you can average those values or take their median. The [article](https://arxiv.org/abs/2211.04085) discusses how you calculate the distances of the objects and how a reduction of the bounding box improves the depth estimation.

**Comment by abhishekt711** [comment]
Thank you so much for helping me out and giving ur time. The point coloud projected on image is working perfectly and also the coloured point cloud is working perfectly. Now can u please help me with the reference code for depth estimation of obstacle?

**Comment by EPVelasco** [comment]
Sorry but I don't have any code on github that does the process.
I'm working on one but I can't make it public yet.

**Comment by af-doom** [comment]
> Thank you so much for helping me out and giving ur time. The point coloud projected on image is working perfectly and also the coloured point cloud is working perfectly. Now can u please help me with the reference code for depth estimation of obstacle?

Hello, have you continued your research on depth estimation
