### ISSUE TITLE
I am using the same hardware as you, but my performance is poor and I have not adjusted the parameters except for the external parameters

### ISSUE THREAD

**Issue by af-doom** [EPVelasco/lidar-camera-fusion#7]
![1](https://user-images.githubusercontent.com/91470350/230522077-1a1a7b12-9230-42b2-8dbb-f16eaea1acf0.png)
![2](https://user-images.githubusercontent.com/91470350/230522085-dc86bb89-f644-4913-9af5-b98eb7bf28e4.png)

**Comment by EPVelasco** [comment]
Hi, I can see from the images you show me that the camera-lidar transformation matrix is not correct. 
![image](https://user-images.githubusercontent.com/35384396/232352926-456caf80-5561-4884-a8e5-7d215f43b05c.png)

As you can see, the LiDAR points on the RGB image do not correspond to the scenario, you have a positioning error in one of the LiDAR-camera axes. I suggest you to recalibrate your camera and LiDAR using the package [lidar_camera_calibration](https://github.com/ankitdhall/lidar_camera_calibration).
