### ISSUE TITLE
Could you explain how you calculate angular_resolution_x,angular_resolution_y,max_angle_width,max_angle_height?

### ISSUE THREAD

**Issue by Gio-giouv** [EPVelasco/lidar-camera-fusion#9]
In the offline node it seems I do not have good results. I am using gazebo simulation and I do not have the actual sensors so instead of calibration I am using tf_echo between camera and lidar frame to get the rotation and translation matrices.

**Comment by EPVelasco** [comment]
Hi, please you can check this [issue](https://github.com/EPVelasco/lidar-camera-fusion/issues/3)

**Comment by Gio-giouv** [comment]
Hello thank you for your response I found them in the end , but I have strange output and I could not understand where is the problem maybe you could help me? The range image is not dense 
![achess](https://user-images.githubusercontent.com/61353529/236404949-1ccdabcd-1f02-409d-aa01-f8ce1e8c3b97.png)
